package com.b2berp.b2bmodel.core;
// Generated Feb 4, 2018 10:28:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses",
        catalog = "erpcommerce"
)
public class Addresses implements java.io.Serializable {

    private Long id;
    private BusinessCompany businessCompany;
    private City city;
    private Clients clients;
    private Country country;
    private State state;
    private User user;
    private Date createdAt;
    private Date updatedAt;
    private String addrTitle;
    private String addrLine1;
    private String addrLine2;
    private String addrLine3;
    private String addrCountry;
    private String addrLat;
    private String addrLong;
    private String addrEmail1;
    private String addrEmail2;
    private String addrPhone1;
    private String addrPhone2;

    public Addresses() {
    }

    public Addresses(Date createdAt, Date updatedAt) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Addresses(BusinessCompany businessCompany, City city, Clients clients, Country country, State state, User user, Date createdAt, Date updatedAt, String addrTitle, String addrLine1, String addrLine2, String addrLine3, String addrCountry, String addrLat, String addrLong, String addrEmail1, String addrEmail2, String addrPhone1, String addrPhone2) {
        this.businessCompany = businessCompany;
        this.city = city;
        this.clients = clients;
        this.country = country;
        this.state = state;
        this.user = user;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.addrTitle = addrTitle;
        this.addrLine1 = addrLine1;
        this.addrLine2 = addrLine2;
        this.addrLine3 = addrLine3;
        this.addrCountry = addrCountry;
        this.addrLat = addrLat;
        this.addrLong = addrLong;
        this.addrEmail1 = addrEmail1;
        this.addrEmail2 = addrEmail2;
        this.addrPhone1 = addrPhone1;
        this.addrPhone2 = addrPhone2;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "business_id")
    public BusinessCompany getBusinessCompany() {
        return this.businessCompany;
    }

    public void setBusinessCompany(BusinessCompany businessCompany) {
        this.businessCompany = businessCompany;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "addr_city")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clients_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "addr_zip")
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "addr_state")
    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Column(name = "addr_title")
    public String getAddrTitle() {
        return this.addrTitle;
    }

    public void setAddrTitle(String addrTitle) {
        this.addrTitle = addrTitle;
    }

    @Column(name = "addr_line1")
    public String getAddrLine1() {
        return this.addrLine1;
    }

    public void setAddrLine1(String addrLine1) {
        this.addrLine1 = addrLine1;
    }

    @Column(name = "addr_line2")
    public String getAddrLine2() {
        return this.addrLine2;
    }

    public void setAddrLine2(String addrLine2) {
        this.addrLine2 = addrLine2;
    }

    @Column(name = "addr_line3")
    public String getAddrLine3() {
        return this.addrLine3;
    }

    public void setAddrLine3(String addrLine3) {
        this.addrLine3 = addrLine3;
    }

    @Column(name = "addr_country")
    public String getAddrCountry() {
        return this.addrCountry;
    }

    public void setAddrCountry(String addrCountry) {
        this.addrCountry = addrCountry;
    }

    @Column(name = "addr_lat", length = 15)
    public String getAddrLat() {
        return this.addrLat;
    }

    public void setAddrLat(String addrLat) {
        this.addrLat = addrLat;
    }

    @Column(name = "addr_long", length = 15)
    public String getAddrLong() {
        return this.addrLong;
    }

    public void setAddrLong(String addrLong) {
        this.addrLong = addrLong;
    }

    @Column(name = "addr_email1")
    public String getAddrEmail1() {
        return this.addrEmail1;
    }

    public void setAddrEmail1(String addrEmail1) {
        this.addrEmail1 = addrEmail1;
    }

    @Column(name = "addr_email2")
    public String getAddrEmail2() {
        return this.addrEmail2;
    }

    public void setAddrEmail2(String addrEmail2) {
        this.addrEmail2 = addrEmail2;
    }

    @Column(name = "addr_phone1", length = 50)
    public String getAddrPhone1() {
        return this.addrPhone1;
    }

    public void setAddrPhone1(String addrPhone1) {
        this.addrPhone1 = addrPhone1;
    }

    @Column(name = "addr_phone2", length = 50)
    public String getAddrPhone2() {
        return this.addrPhone2;
    }

    public void setAddrPhone2(String addrPhone2) {
        this.addrPhone2 = addrPhone2;
    }

}
