package com.b2berp.b2bmodel.core;
// Generated Feb 4, 2018 10:28:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AttributeTypes generated by hbm2java
 */
@Entity
@Table(name = "attribute_types",
         catalog = "erpcommerce"
)
public class AttributeTypes implements java.io.Serializable {

    private Long id;
    private AttributeTypes attributeTypes;
    private BusinessCompany businessCompany;
    private Date createdAt;
    private Date updatedAt;
    private Integer active;
    private String attrName;
    private int isMarker;
    private Integer hasValues;
    private Long parent;
    private int isGlobal;
    private Set<AttributeTypes> attributeTypeses = new HashSet<AttributeTypes>(0);

    public AttributeTypes() {
    }

    public AttributeTypes(Date createdAt, Date updatedAt, String attrName, int isMarker, int isGlobal) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.attrName = attrName;
        this.isMarker = isMarker;
        this.isGlobal = isGlobal;
    }

    public AttributeTypes(AttributeTypes attributeTypes, BusinessCompany businessCompany, Date createdAt, Date updatedAt, Integer active, String attrName, int isMarker, Integer hasValues, Long parent, int isGlobal, Set<AttributeTypes> attributeTypeses) {
        this.attributeTypes = attributeTypes;
        this.businessCompany = businessCompany;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.active = active;
        this.attrName = attrName;
        this.isMarker = isMarker;
        this.hasValues = hasValues;
        this.parent = parent;
        this.isGlobal = isGlobal;
        this.attributeTypeses = attributeTypeses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public AttributeTypes getAttributeTypes() {
        return this.attributeTypes;
    }

    public void setAttributeTypes(AttributeTypes attributeTypes) {
        this.attributeTypes = attributeTypes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "business_id")
    public BusinessCompany getBusinessCompany() {
        return this.businessCompany;
    }

    public void setBusinessCompany(BusinessCompany businessCompany) {
        this.businessCompany = businessCompany;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Column(name = "active")
    public Integer getActive() {
        return this.active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    @Column(name = "attr_name", nullable = false)
    public String getAttrName() {
        return this.attrName;
    }

    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    @Column(name = "isMarker", nullable = false)
    public int getIsMarker() {
        return this.isMarker;
    }

    public void setIsMarker(int isMarker) {
        this.isMarker = isMarker;
    }

    @Column(name = "hasValues")
    public Integer getHasValues() {
        return this.hasValues;
    }

    public void setHasValues(Integer hasValues) {
        this.hasValues = hasValues;
    }

    @Column(name = "parent")
    public Long getParent() {
        return this.parent;
    }

    public void setParent(Long parent) {
        this.parent = parent;
    }

    @Column(name = "isGlobal", nullable = false)
    public int getIsGlobal() {
        return this.isGlobal;
    }

    public void setIsGlobal(int isGlobal) {
        this.isGlobal = isGlobal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributeTypes")
    public Set<AttributeTypes> getAttributeTypeses() {
        return this.attributeTypeses;
    }

    public void setAttributeTypeses(Set<AttributeTypes> attributeTypeses) {
        this.attributeTypeses = attributeTypeses;
    }

}
