package com.b2berp.b2bmodel.core;
// Generated Feb 4, 2018 10:28:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country",
         catalog = "erpcommerce"
)
public class Country implements java.io.Serializable {

    private String countryName;
    private String countryIsoAlpha2;
    private String countryIsoAlpha3;
    private Integer countryIsoNumeric;
    private String countryFlag;
    private Date createdAt;
    private Date updatedAt;
    private Set<State> states = new HashSet<State>(0);
    private Set<Addresses> addresseses = new HashSet<Addresses>(0);

    public Country() {
    }

    public Country(String countryName, Date createdAt, Date updatedAt) {
        this.countryName = countryName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Country(String countryName, String countryIsoAlpha2, String countryIsoAlpha3, Integer countryIsoNumeric, String countryFlag, Date createdAt, Date updatedAt, Set<State> states, Set<Addresses> addresseses) {
        this.countryName = countryName;
        this.countryIsoAlpha2 = countryIsoAlpha2;
        this.countryIsoAlpha3 = countryIsoAlpha3;
        this.countryIsoNumeric = countryIsoNumeric;
        this.countryFlag = countryFlag;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.states = states;
        this.addresseses = addresseses;
    }

    @Id

    @Column(name = "country_name", unique = true, nullable = false)
    public String getCountryName() {
        return this.countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @Column(name = "country_iso_alpha2", length = 2)
    public String getCountryIsoAlpha2() {
        return this.countryIsoAlpha2;
    }

    public void setCountryIsoAlpha2(String countryIsoAlpha2) {
        this.countryIsoAlpha2 = countryIsoAlpha2;
    }

    @Column(name = "country_iso_alpha3", length = 3)
    public String getCountryIsoAlpha3() {
        return this.countryIsoAlpha3;
    }

    public void setCountryIsoAlpha3(String countryIsoAlpha3) {
        this.countryIsoAlpha3 = countryIsoAlpha3;
    }

    @Column(name = "country_iso_numeric")
    public Integer getCountryIsoNumeric() {
        return this.countryIsoNumeric;
    }

    public void setCountryIsoNumeric(Integer countryIsoNumeric) {
        this.countryIsoNumeric = countryIsoNumeric;
    }

    @Column(name = "country_flag")
    public String getCountryFlag() {
        return this.countryFlag;
    }

    public void setCountryFlag(String countryFlag) {
        this.countryFlag = countryFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set<State> getStates() {
        return this.states;
    }

    public void setStates(Set<State> states) {
        this.states = states;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }

    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }

}
