package com.b2berp.b2bmodel.core;
// Generated Feb 4, 2018 10:28:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mediaformat generated by hbm2java
 */
@Entity
@Table(name = "mediaformat",
         catalog = "erpcommerce",
         uniqueConstraints = @UniqueConstraint(columnNames = "mediaformat_name")
)
public class Mediaformat implements java.io.Serializable {

    private Long id;
    private Mediaformat mediaformat;
    private Modules modules;
    private User user;
    private String mediaformatName;
    private String folderName;
    private int width;
    private int height;
    private String comments;
    private char isParent;
    private Date updatedAt;
    private Date createdAt;
    private Set<Mediaformat> mediaformats = new HashSet<Mediaformat>(0);

    public Mediaformat() {
    }

    public Mediaformat(String folderName, int width, int height, char isParent, Date updatedAt, Date createdAt) {
        this.folderName = folderName;
        this.width = width;
        this.height = height;
        this.isParent = isParent;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
    }

    public Mediaformat(Mediaformat mediaformat, Modules modules, User user, String mediaformatName, String folderName, int width, int height, String comments, char isParent, Date updatedAt, Date createdAt, Set<Mediaformat> mediaformats) {
        this.mediaformat = mediaformat;
        this.modules = modules;
        this.user = user;
        this.mediaformatName = mediaformatName;
        this.folderName = folderName;
        this.width = width;
        this.height = height;
        this.comments = comments;
        this.isParent = isParent;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.mediaformats = mediaformats;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mediaformat_id")
    public Mediaformat getMediaformat() {
        return this.mediaformat;
    }

    public void setMediaformat(Mediaformat mediaformat) {
        this.mediaformat = mediaformat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modules_id")
    public Modules getModules() {
        return this.modules;
    }

    public void setModules(Modules modules) {
        this.modules = modules;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "mediaformat_name", unique = true)
    public String getMediaformatName() {
        return this.mediaformatName;
    }

    public void setMediaformatName(String mediaformatName) {
        this.mediaformatName = mediaformatName;
    }

    @Column(name = "folder_name", nullable = false, length = 50)
    public String getFolderName() {
        return this.folderName;
    }

    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }

    @Column(name = "width", nullable = false)
    public int getWidth() {
        return this.width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    @Column(name = "height", nullable = false)
    public int getHeight() {
        return this.height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    @Column(name = "comments", length = 500)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "isParent", nullable = false, length = 1)
    public char getIsParent() {
        return this.isParent;
    }

    public void setIsParent(char isParent) {
        this.isParent = isParent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaformat")
    public Set<Mediaformat> getMediaformats() {
        return this.mediaformats;
    }

    public void setMediaformats(Set<Mediaformat> mediaformats) {
        this.mediaformats = mediaformats;
    }

}
