package com.b2berp.b2bmodel.core;
// Generated Feb 4, 2018 10:28:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name = "modules",
         catalog = "erpcommerce"
)
public class Modules implements java.io.Serializable {

    private Long id;
    private Modules modules;
    private User user;
    private Date createdAt;
    private Date updatedAt;
    private int active;
    private String moduleName;
    private String moduleTitle;
    private String moduleDesc;
    private String moduleImage;
    private String moduleType;
    private int priorityIndex;
    private String moduleUrl;
    private String moduleCss;
    private String moduleIconClass;
    private int hasChildren;
    private Set<Mediaformat> mediaformats = new HashSet<Mediaformat>(0);
    private Set<Modules> moduleses = new HashSet<Modules>(0);
    private Set<BusinessCompany> businessCompanies = new HashSet<BusinessCompany>(0);

    public Modules() {
    }

    public Modules(Date createdAt, Date updatedAt, int active, String moduleName, String moduleTitle, String moduleType, int priorityIndex, int hasChildren) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.active = active;
        this.moduleName = moduleName;
        this.moduleTitle = moduleTitle;
        this.moduleType = moduleType;
        this.priorityIndex = priorityIndex;
        this.hasChildren = hasChildren;
    }

    public Modules(Modules modules, User user, Date createdAt, Date updatedAt, int active, String moduleName, String moduleTitle, String moduleDesc, String moduleImage, String moduleType, int priorityIndex, String moduleUrl, String moduleCss, String moduleIconClass, int hasChildren, Set<Mediaformat> mediaformats, Set<Modules> moduleses, Set<BusinessCompany> businessCompanies) {
        this.modules = modules;
        this.user = user;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.active = active;
        this.moduleName = moduleName;
        this.moduleTitle = moduleTitle;
        this.moduleDesc = moduleDesc;
        this.moduleImage = moduleImage;
        this.moduleType = moduleType;
        this.priorityIndex = priorityIndex;
        this.moduleUrl = moduleUrl;
        this.moduleCss = moduleCss;
        this.moduleIconClass = moduleIconClass;
        this.hasChildren = hasChildren;
        this.mediaformats = mediaformats;
        this.moduleses = moduleses;
        this.businessCompanies = businessCompanies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent")
    public Modules getModules() {
        return this.modules;
    }

    public void setModules(Modules modules) {
        this.modules = modules;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Column(name = "active", nullable = false)
    public int getActive() {
        return this.active;
    }

    public void setActive(int active) {
        this.active = active;
    }

    @Column(name = "module_name", nullable = false)
    public String getModuleName() {
        return this.moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    @Column(name = "module_title", nullable = false)
    public String getModuleTitle() {
        return this.moduleTitle;
    }

    public void setModuleTitle(String moduleTitle) {
        this.moduleTitle = moduleTitle;
    }

    @Column(name = "module_desc")
    public String getModuleDesc() {
        return this.moduleDesc;
    }

    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc;
    }

    @Column(name = "module_image")
    public String getModuleImage() {
        return this.moduleImage;
    }

    public void setModuleImage(String moduleImage) {
        this.moduleImage = moduleImage;
    }

    @Column(name = "module_type", nullable = false)
    public String getModuleType() {
        return this.moduleType;
    }

    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    @Column(name = "priority_index", nullable = false)
    public int getPriorityIndex() {
        return this.priorityIndex;
    }

    public void setPriorityIndex(int priorityIndex) {
        this.priorityIndex = priorityIndex;
    }

    @Column(name = "module_url")
    public String getModuleUrl() {
        return this.moduleUrl;
    }

    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl;
    }

    @Column(name = "module_css")
    public String getModuleCss() {
        return this.moduleCss;
    }

    public void setModuleCss(String moduleCss) {
        this.moduleCss = moduleCss;
    }

    @Column(name = "module_icon_class")
    public String getModuleIconClass() {
        return this.moduleIconClass;
    }

    public void setModuleIconClass(String moduleIconClass) {
        this.moduleIconClass = moduleIconClass;
    }

    @Column(name = "hasChildren", nullable = false)
    public int getHasChildren() {
        return this.hasChildren;
    }

    public void setHasChildren(int hasChildren) {
        this.hasChildren = hasChildren;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
    public Set<Mediaformat> getMediaformats() {
        return this.mediaformats;
    }

    public void setMediaformats(Set<Mediaformat> mediaformats) {
        this.mediaformats = mediaformats;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
    public Set<Modules> getModuleses() {
        return this.moduleses;
    }

    public void setModuleses(Set<Modules> moduleses) {
        this.moduleses = moduleses;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "business_modules", catalog = "erpcommerce", joinColumns = {
        @JoinColumn(name = "modules_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "business_company_id", nullable = false, updatable = false)})
    public Set<BusinessCompany> getBusinessCompanies() {
        return this.businessCompanies;
    }

    public void setBusinessCompanies(Set<BusinessCompany> businessCompanies) {
        this.businessCompanies = businessCompanies;
    }

}
